### ISSUE TITLE
Can't install on standard user

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1216]
Hi, I can't install ImageGlass on the standard user.
Please make an installation for the current user/all users.
MSI packages don't support this, you should make an EXE installation.
![image](https://user-images.githubusercontent.com/23485114/149637898-eb52337d-afc2-41f5-951d-4ffd8514e329.png)
![image](https://user-images.githubusercontent.com/23485114/149637918-a791a190-0516-4a8e-8ccf-ccb6742d96b4.png)
Thanks.

**Comment by d2phap** [comment]
Added user selection in MSI x64 installer for v8.4

**Comment by xmha97** [comment]
This issue has not been resolved yet :(
I don't have admin rights.
I think the problem is that the installer wants to add the app shortcut to all users.

https://user-images.githubusercontent.com/23485114/150463579-ddefee05-ac73-42ab-87d6-c3b4db56a0c8.mp4

**Comment by d2phap** [comment]
I see, thanks for the video!

**Comment by d2phap** [comment]
This issue was fixed some time ago

**Comment by xmha97** [comment]
@d2phap This problem is still not solved and it is exactly according to the video I sent.
I don't think it is possible to install without admin permission for the MSI installer, please make an EXE installer like before.

**Comment by d2phap** [comment]
hmm, I will not add support for this, since the AdvancedInstaller does not have a fix for their product: https://www.advancedinstaller.com/forums/viewtopic.php?t=50421

**Comment by xmha97** [comment]
> hmm, I will not add support for this, since the AdvancedInstaller does not have a fix for their product: https://www.advancedinstaller.com/forums/viewtopic.php?t=50421

Ok, but you can create an installer using other apps like INNO Setup.

**Comment by xmha97** [comment]
> Hmm, I will not add support for this, since the AdvancedInstaller does not have a fix for their product: https://www.advancedinstaller.com/forums/viewtopic.php?t=50421

@d2phap 
I noticed the MSI installer supports this feature. FirefoxPWA and ScreenToGif installers are MSI and can install the app without admin privileges.
Please see their source code, maybe you can solve the problem.
https://github.com/filips123/PWAsForFirefox
https://github.com/NickeManarin/ScreenToGif

![Animation](https://github.com/d2phap/ImageGlass/assets/23485114/ef3bc968-4334-4446-b703-6df3e524ea6a)
