### ISSUE TITLE
ImageGlass installer has wrong default installation directory and creates unnecessary folder in 32-bit Windows

### ISSUE THREAD

**Issue by SilverKnight-Z** [d2phap/ImageGlass#1265]
### System information:
- Windows OS version: Windows 7 Starter SP1 32-bit 

- ImageGlass version: 8.5.1.22 (x86 Installer): 

### To Reproduce

- Open ImageGlass 8.5.1.22 (x86) MSI Installer
- Follow the installation instructions
- When the installer asks for the location where you want to install ImageGlass, change the default location to "C:\Program Files\ImageGlass\".
- Continue with the installation and wait for it to finish.
- Look for the installation folder

### Actual behavior:
- I have to change the default install location to "C:\Program Files\ImageGlass" on 32-bit Windows.
- The installer installs most of ImageGlass files in that location
- The installer creates the location "C:\Program Files (x86)\ImageGlass", where it installs a couple of shortcuts, even though I have given it another location

### Expected behavior:
- The default installation location is "C:\Program Files\ImageGlass\" on 32-bit Windows.
- All ImageGlass files are installed in the specified folder, either default or custom, so the installer does not create the location "C:\Program Files (x86)\ImageGlass\" on 32-bit Windows.

### Screenshots:
![20220122_201701.jpg](https://user-images.githubusercontent.com/82909608/150694432-d6c8f94a-0601-420c-87bf-e00f60d88b73.jpg)

### Additional context:
On 32-bit systems the default installation location should be "C:\Program Files" not "C:\Program Files (x86)\ImageGlass" as  that location is for 32-bit applications on 64-bit systems.
This does not happen in the ImageGlass 8.3.11.21 (x86) installer.

**Comment by d2phap** [comment]
It should be fixed in ImageGlass 8.6

**Comment by Anton-V-K** [comment]
This issue still happens when installing version 8.7.11.6 in Windows 10 22H2 32-bit:
![image](https://github.com/d2phap/ImageGlass/assets/20116984/ec68fb1e-28e4-495e-95c6-cf9de110ac97)
