### ISSUE TITLE
Trying to Unregister File Extensions

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1360]
Trying to Unregister File Extensions

- I Think, The option works correctly, but wrong popup comming
**`Unable to delete registered file extensions of ImageGlass app`**

.

https://user-images.githubusercontent.com/98110551/173389186-4f9475d5-14fc-4cf3-a86b-43946f4f29ee.mp4

**Comment by d2phap** [comment]
This issues is fixed in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904)!
You can set / unset the default photo viewer though main menu.

![image](https://user-images.githubusercontent.com/3154213/188636890-dab44f71-4502-4c02-8e3d-492bbcde491f.png)


![image](https://user-images.githubusercontent.com/3154213/188636809-b1ddcdc7-90a4-4799-85d2-b0a4617f28d3.png)


![image](https://user-images.githubusercontent.com/3154213/188637008-dadf5ae0-00de-4418-8167-ff8a3c32ef4d.png)

**Comment by TheRealSamChaney** [comment]
This does not fix the problem. The "Unregister extensions" button in the ImageGlass settings still gives the error in Windows 10 "Unable to delete the registered file extensions of ImageGlass app"
