### ISSUE TITLE
Failed to initialize Webview2! Error 0x800700AA at EnsureWeb2Async() due to folder permission

### ISSUE THREAD

**Issue by suyangzuo** [d2phap/ImageGlass#1620]
### System information:
 - Windows OS version: 11 22H2
 - ImageGlass version: beta 5

### To Reproduce
1. Open "Settings"
2. An empty Settings window with a Error box will popup.

### Screenshots:
<img width="516" alt="5RBjS23SDO" src="https://github.com/d2phap/ImageGlass/assets/50766353/4ef79549-a984-4bed-a8da-4b2643cf04cd">

### Additional context:
Have tried use administrator mode and reboot computer, doens't work.

**Comment by d2phap** [comment]
Do you have [WebView2 Runtime x64](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) installed in your machine?

Since v9.0 beta 4, ImageGlass requires WebView2 for full functions

**Comment by suyangzuo** [comment]
> Do you have [WebView2 Runtime x64](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) installed in your machine?
> 
> Since v9.0 beta 4, ImageGlass requires WebView2 for full functions

I tried download WebView2 Runtime x64 and install it, it shows a dialog box as below:
<img width="537" alt="1siAJe9vtc" src="https://github.com/d2phap/ImageGlass/assets/50766353/24788b72-a294-4448-93e6-8d8c262c5b4d">

I think it means I have already installed it before.

**Comment by suyangzuo** [comment]
> Do you have [WebView2 Runtime x64](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) installed in your machine?
> 
> Since v9.0 beta 4, ImageGlass requires WebView2 for full functions

beta 4 is running fine. Just beta 5 cannot open Settings window.

**Comment by d2phap** [comment]
Can you open the About window of beta 4 and beta 5?

**Comment by d2phap** [comment]
Another thing you can try is deleting the folder `WebUIData`

**Comment by suyangzuo** [comment]
I have already solved this problem.
The issue is  my "ImageGlass" folder doesn't have write permission in C drive.
I add a  "Everyone" username in folder properties and give it "Full access" permission then everything runs OK !

**Comment by d2phap** [comment]
Thanks for the info. I will add a check for this

**Comment by d2phap** [comment]
It should be fixed in [ImageGlass 9.0 RC](https://github.com/d2phap/ImageGlass/releases/tag/9.0.6.1008)

**Comment by yaneony** [comment]
Problem still exist on newly installed Windows 11. All runtimes are installed.
