### ISSUE TITLE
Bug when changing default keys

### ISSUE THREAD

**Issue by mak7im01** [d2phap/ImageGlass#1988]
### System information
- Windows OS version: 
Windows 11 Pro
22H2
‎04.‎10.‎2023
ОС	22621.3958
Windows Feature Experience Pack 1000.22700.1026.0

- ImageGlass version: 9.1.8.723
- ImageGlass release: Classic

### To Reproduce
When changing the combinations Ctrl+Shift+C to Ctrl+C, everything works and is displayed, but after some time, more than 5 minutes, the values ​​are automatically reset to Ctrl+Shift+Alt+

### Actual behavior
```
"MenuHotkeys": {
    "MnuCopyFile": [
      "Ctrl+C"
    ],
    "MnuCopyImageData": [
      "Ctrl+Shift+C"
    ]
  },
```
Changes over time to this
```
"MenuHotkeys": {
    "MnuCopyFile": [
      "Ctrl+Shift+Alt+"
    ],
    "MnuCopyImageData": [
      "Ctrl+Shift+Alt+"
    ]
  },

```
### Expected behavior
Please help me solve this problem

**Comment by mak7im01** [comment]
[igconfig (1).json](https://github.com/user-attachments/files/16675354/igconfig.1.json)
[igconfig (2).json](https://github.com/user-attachments/files/16675353/igconfig.2.json)

**Comment by d2phap** [comment]
It does not happen to me, I'm using English (US) keyboard layout. What keyboard layout are you using?
<img height="200" src="https://github.com/user-attachments/assets/d1a72370-6ed3-448c-b250-2aef40ba732e" />


To correctly get the hotkey, you should open Settings > Tools > click "Add" button > click "Add hotkey" button, the "Press hotkeys" dialog appears allow you to press your hotkey.
Use this hotkey for the `MenuHotkeys`.

![image](https://github.com/user-attachments/assets/5e1840b5-2bc1-47ed-a322-1ffd48c3a244)

**Comment by mak7im01** [comment]
![2024-08-23 135816](https://github.com/user-attachments/assets/30192597-6703-449a-9055-61b81bcee28b)

I added the key combination using your method (I read it in previous messages). Everything is correct.
Thanks to your tip, I found out that it depends on the default language. I edit file `MenuHotkeys` with the English keyboard enabled, the key combination in the program does not reset, but as soon as I switch the keyboard language to another, in my case to Russian (I tried others different from English) and the key combination immediately becomes **Ctrl+Shift+Alt+**
This is not very convenient and not very correct in my opinion.

**Comment by mak7im01** [comment]
https://github.com/d2phap/ImageGlass/issues/1988#issuecomment-2298698793
File igconfig(1).json before switching language, file igconfig(2).json after switching language. Changes occur automatically

**Comment by mak7im01** [comment]
![2024-08-23 164440](https://github.com/user-attachments/assets/9ee058a2-95ad-4d56-a538-df2e3bbf543a)
Also, the command that is reset after switching the language is set by default for this action

**Comment by d2phap** [comment]
Okay I just pushed a fix, will include this in the next release

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.2 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.1104)

**Comment by mak7im01** [comment]
Updated to 9.1.8.1104. This bug still remains. Everything is still replaced by "Ctrl+Shift+Alt+"

**Comment by mak7im01** [comment]
> Исправлено в [бета-версии ImageGlass 9.2](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.1104)

Updated to 9.1.8.1104. This bug still remains. Everything is still replaced by "Ctrl+Shift+Alt+"

**Comment by d2phap** [comment]
@mak7im01 Do you mind to test this build if it's fixed?
https://drive.google.com/file/d/12ibBt7giHU1ZDC56yX1jVqz8lYMF7w0Q/view?usp=sharing

**Comment by mak7im01** [comment]
> @mak7im01 In this version the bug is fixed. Now the values ​​are not reset automatically

Thank you

**Comment by mak7im01** [comment]
> @mak7im01 Не могли бы вы протестировать эту сборку, чтобы убедиться, что она исправлена? https://drive.google.com/file/d/12ibBt7giHU1ZDC56yX1jVqz8lYMF7w0Q/view?usp=sharing

In this version the bug is fixed. Now the values ​​are not reset automatically

Thank

**Comment by d2phap** [comment]
Published [ImageGlass 9.2.0.1208 - Maroon 4](https://github.com/d2phap/ImageGlass/releases/tag/9.2.0.1208) with this fix.
