### ISSUE TITLE
Win+Arrow key selects first image

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#206]
### Expected behavior:
Don't change image when pressing hotkey

### Actual behavior:
Pressing hotkey selects the first image in folder

### Steps to reproduce:
1. Open an image thats not the first image in a folder
2. Press Windows key + right arrow key to move the window to the side of the monitor

### System info:
- ImageGlass version: 4.0.4.15
- OS version: Windows 8

**Comment by d2phap** [comment]
Hi @Keith94 
This defect was fixed since #148 (v4.0)
I also tested in my machine (Win7 and Win10), it works as expected. 

Any body get the same problem?

**Comment by Keith94** [comment]
I'm still experiencing this issue 100% of the time on a fresh install of Windows 10. :-(

**Comment by d2phap** [comment]
Fixed in `develop` branch
