### ISSUE TITLE
Set as desktop background is not working

### ISSUE THREAD

**Issue by tslin306** [d2phap/ImageGlass#287]
### Expected behavior:
- Windows Background image should changed when selecting "Set as desktop background"

### Actual behavior:
- Nothing is happening.

### Steps to reproduce:
1. This issue started after upgrading to 4.5.11.27 stable release.

### System info:
- ImageGlass version: 4.5.11.27
- OS version: Microsoft Windows 10 Home Edition (x64)

### Other info:
- Set as desktop background is working in 4.5.11.14_Moon release. But in there, after image is deleted, it is not automatically display next image. I already tried to re-install, uninstall whole ImageGlass and restart PC with no luck. Please help.

Cheers!

**Comment by d2phap** [comment]
Confirmed this `Set as desktop background` bug.
Thanks

**Comment by fire-eggs** [comment]
I can't commit to the develop branch so here's the change.

The first line of `mnuMainSetAsDesktop_Click` (line 3174?) should read:
```
            if (GlobalSetting.IsTempMemoryData || 
                !File.Exists(GlobalSetting.ImageList.GetFileName(GlobalSetting.CurrentIndex)))
                return;
```

**Comment by d2phap** [comment]
Thanks @fire-eggs for this discovery. Fixed in `develop` branch

**Comment by SourceCipher** [comment]
Still having this issue. Setting the image as a desktop background doesn't work.

**Comment by d2phap** [comment]
Hi @SourceCipher,
The fixes is still under `develop` branch which means that if you use the latest `stable` version, you will still encounter the same issue.

If you want to try the latest build of `develop` branch, you can download here (I call it as ***ImageGlass Moon***): http://www.imageglass.org/moon
