### ISSUE TITLE
Multi-Monitor Support

### ISSUE THREAD

**Issue by staticninja** [d2phap/ImageGlass#49]
After moving ImageGlass to a monitor attached to a laptop, closing ImageGlass, disconnecting the external monitor, and reopening ImageGlass it fails to load in the primary monitor and fails to respond to Win+Left arrow to move it to visible space.

**Comment by d2phap** [comment]
Hi @staticninja 

Thanks for your report!

**Comment by d2phap** [comment]
From Robert Schwabe:

I have a strange bug on Win 10. I opened ImageGlass while having a second monitor connected to my notebook, and now every time I try to open ImageGlass without a second screen connected it will still open on the "second screen". I can see from the maximize/minimize animation that the window flies out of the right side of the desktop with no way of moving it back to the visible screen area. Windows hotkeys for moving between different screens don't work since there is no actual second screen connected. Therefore, I can't use ImageGlass unless I connect a second screen so that I can see it there and move it back to the primary screen. Very annoying.﻿ 

Steps to replicate:
1. Connect second monitor to a computer
2. Set Windows to extend desktop (not duplicate)
3. Open ImageGlass, move window to second screen
4. Close ImageGlass
5. Disconnect second monitor
6. Open ImageGlass
Expected behavior: ImageGlass opens on the visible screen area
Actual behavior: ImageGlass opens outside of the visible screen area where the second screen was before﻿

**Comment by Feagorn** [comment]
One more thing about multi monitor support. In my configuration I do have 3 monitors attached.
Currently the ImageGlass windows opens randomly on on of the monitors with a bias to monitor 2. I cannot figure out a pattern as for what monitor is being selected while the program starts. It is not fixed, it is not attached to the mouse pointer position.
Some settings or clarification in this matter would be of help.

**Comment by d2phap** [comment]
This issue is fixed (similar to #117)

ImageGlass Moon for testing:
http://imageglass.org/upload/moon/ImageGlass_3.x_07032017.zip

**Comment by 360path** [comment]
The problem still exists with version 9.0.10.201. When it is focused (on the non-existent secondary screen) I can press Alt-F etc. to open the menu, and opening Settings opens on the screen I can see.
