### ISSUE TITLE
HEIC opening is somewhat slow

### ISSUE THREAD

**Issue by kleuter** [d2phap/ImageGlass#995]
### System information:
 - Windows OS version: 10x64
 - ImageGlass version:  8

Before opening a 1MB image I need to wait ~3 seconds on my Core i7 8700K

Any change to get it improved? Thanks.

**Comment by d2phap** [comment]
Hi @kleuter 

> Before opening a 1MB image ***I need to wait ~3 seconds*** on my Core i7 8700K

Can you describe more about 3 seconds.
- Is that the time you waited for ImageGlass window open, or to view the image?
- Can you attach your HEIC file, it's better for investigation?
 
Thanks!

**Comment by kleuter** [comment]
The window opens normally for a .NET app, not instantly as native apps but fine.
After it opens I have to wait the file to be rendered.
Can't attach a file, it happens to any file from the library, even for small files.

I can record a video if you'd like

**Comment by d2phap** [comment]
You can attach a zip file instead

**Comment by kleuter** [comment]
[IMG_8080.zip](https://github.com/d2phap/ImageGlass/files/6097949/IMG_8080.zip)

**Comment by fire-eggs** [comment]
Here's my experience on my Win7x64, I7-4790.

Your sample image takes me about 2 seconds to load. I get the impression that IG 8.0 takes a smidge longer than IG 7.6 or the latest IG Moon. You might give the latter a try.

IG 7.6/Moon takes me three seconds to load a 5000x8889 pixel HEIC (see issue #647); IG 8.0 takes about 5 seconds. [A larger _resolution_ image may take longer than a larger disk size.]

You don't tell us if you are loading files across the network. Mine are on a local, spinning rust disk.

**Comment by kleuter** [comment]
Local SSD drive, I don't think I must use the older version if 8.0 is the latest

**Comment by fire-eggs** [comment]
Sorry if I was unclear. The [ImageGlass Moon](https://imageglass.org/moon) releases are newer than 8.0 but might not be considered "stable" by some. Issue #977 is a HEIC related bug which was addressed in the most recent ImageGlass Moon.

**Comment by dingshi** [comment]
I'm experiencing similar problem. ~2 seconds for the app to load, another 3 seconds for the image to load, Most annoyingly the loading message at the center of the screen stays on for about 10 seconds after the image is rendered. Noticed CPU keeps up in the high during the entire 12 seconds. Most my files are local on SSD, and around 8-10 MB in size., Installed the Moon version. Same issue., Windows 10 x64, CPU is i7-7820X

**Comment by timea-techgirl** [comment]
This problem still exists, HEIC files are very slow to load, takes 2 seconds. Tested all versions, spider, moon, beta.

**Comment by MoemenShahawy** [comment]
Issue still persists. VERY slow loading of HEIC images, which is almost all pictures taken with any modern iphone
There needs to be a solution. I see the thread is since early 2021 and now we're going into 2023 in 2 days

**Comment by d2phap** [comment]
HEIC format is always slower compared to others such as JPG, PNG, JXL,... Unfortunately, ImageGlass does not have built-in decoders, it uses the third-party library Magick.NET which also uses other third-party libraries to decode the image formats. ImageGlass can only help by preloading the images into memory. Hence, there is no fix for this.
